name: Docker Compose Build and Push

on:
  push:
    branches:
      - dev  # Adjust to the branch you want to trigger the workflow

env:
  IMAGE_NAME: sbhardw7/open-telemetry
  DEMO_VERSION: dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sbhardw7@umd.edu
          password: IndraUMD@2931

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo mkdir -p ~/.docker/cli-plugins/
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          sudo chmod +x ~/.docker/cli-plugins/docker-compose
          sudo docker compose version

      # Step 4: Build the images using Docker Compose
      - name: Docker Compose Build
        run: sudo docker compose build

      # Step 5: Print displayed images
      - name: Docker Compose list
        run: sudo docker images -a

      # Step 6: Push the images using Docker Compose
      - name: Docker Compose Push
        run: | 
          sudo docker push $IMAGE_NAME:$DEMO_VERSION-accountingservice
