name: Docker Compose Build and Push

on:
  push:
    branches:
      - dev  # Adjust to the branch you want to trigger the workflow


env: 
  DEMO_VERSION: latest-release

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sbhardw7@umd.edu
          password: IndraUMD@2931

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          echo "This is env var : $DEMO_VERSION"
          sudo mkdir -p ~/.docker/cli-plugins/
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          sudo chmod +x ~/.docker/cli-plugins/docker-compose
          sudo docker compose version
        env: 
          DEMO_VERSION: latest-release

      # Step 4: Build the images using Docker Compose
      - name: Docker Compose Build
        run: sudo DEMO_VERSION=$DEMO_VERSION docker compose build
        env: 
          DEMO_VERSION: latest-release

      # Step 4: Print displayed images
      - name: Docker Compose list
        run: sudo docker images -a

      # Step 6: Push the images using Docker Compose
      - name: Docker Compose Push
        run: | 
          IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "^sbhardw7")
          for IMAGE in $IMAGES; do
            echo "Pushing $IMAGE..."
            docker push $IMAGE || { echo "Failed to push $IMAGE"; exit 1; }
          done
          echo "All images pushed successfully!"
        env: 
          DEMO_VERSION: latest-release
